/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_upchina_Hello */

#ifndef _Included_com_upchina_Hello
#define _Included_com_upchina_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_upchina_Hello
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_upchina_Hello_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
