/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_upchina_LogicMap */

#ifndef _Included_com_upchina_LogicMap
#define _Included_com_upchina_LogicMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_upchina_LogicMap
 * Method:    create
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_upchina_LogicMap_create
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_upchina_LogicMap
 * Method:    searchNodeByLatLng
 * Signature: (DD)I
 */
JNIEXPORT jint JNICALL Java_com_upchina_LogicMap_searchNodeByLatLng
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_upchina_LogicMap
 * Method:    describe
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_upchina_LogicMap_describe
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
